<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            // ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            // ->prependStylesheet($this->basePath('css/bootstrap.min.css'))

        ?>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!-- Scripts -->
        <?= $this->headScript()
            // ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->appendFile($this->basePath('js/jquery-3.1.0.min.js'))
            ->appendFile($this->basePath('js/script.js'))
        ?>
        <!-- Compiled and minified CSS -->

        <!-- Compiled and minified JavaScript -->
    </head>
    <body>
        <nav>
            <div class="nav-wrapper">
              <ul id='nav-mobile' class="left">
                  <li><a href="<?= $this->url('pokemon_home') ?>">Pokémon</a></li>
                  <li><a href="<?= $this->url('type_home') ?>">Type</a></li>
              </ul>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2017 - <?= date('Y') ?> by Maxence, Victor, Cyriaque, Steven</p>
            </footer>
        </div>

        <!-- <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script> -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.0/js/materialize.min.js"></script>
        <?= $this->inlineScript() ?>


    </body>
</html>
