<div class="row">
  <div class="row">
    <h1>Modification d'un Pokémon</h1>
  </div>
  <?php
  $form = $this->form;
  $form->prepare();
  ?>


  <?php echo $this->form()->openTag($form); ?>

  <div class="row">
      <div class="input-field col s12">
        <?php echo $this->formRow($form->get('national_id')); ?>
        <label>National ID</label>
      </div>
  </div>
  <div class="row">
      <div class="input-field col s12">
        <?php echo $this->formRow($form->get('name')); ?>
        <label>Name</label>
      </div>
  </div>
  <div class="row">
      <div class="input-field col s12">
        <?php echo $this->formRow($form->get('description')); ?>
        <label>Description</label>
      </div>
  </div>
  <div class="row">
      <div class="input-field col s12">
        <?php echo $this->formRow($form->get('type1')); ?>
        <label>Type 1</label>
      </div>
  </div>
  <div class="row">
      <div class="input-field col s12">
        <?php echo $this->formRow($form->get('type2')); ?>
        <label>Type 2</label>
      </div>
  </div>
  <div class="row">
      <div class="input-field col s12">
        <?php echo $this->formRow($form->get('evolution')); ?>
        <label>Evolution</label>
      </div>
  </div>

  <?php echo $this->formRow($form->get('id')); ?>
  <?php echo $this->formSubmit($form->get('submit')); ?>
  <?php echo $this->form()->closeTag(); ?>

</div>
