<div class="container">
  <h3>Pokemons</h3>

  <div class="row">
    <div class="collection">
    <?php if (!empty($this->pokemons)) : ?>
        <?php foreach ($this->pokemons as $pokemon) : ?>

                      <a class='collection-item' href="<?php echo $this->url(
                        'pokemon_show', [
                          'pokemonName' => $pokemon->getName()
                        ]); ?>">
                        <?php echo $this->escapeHtml($pokemon->getName()); ?>
                      </a>

        <?php endforeach; ?>
    <?php else : ?>
        <div>Aucun Pokémon à afficher</div>
    <?php endif; ?>
    </div>
    <a class="waves-effect waves-light btn" href="<?php echo $this->url("pokemon_add"); ?>">Ajouter un Pokémon</a>
  </div>

    <?php
        echo $this->paginationControl(
          $this->pokemons,
          'Sliding',
          'partial/pagination',
          ['route' => 'pokemon_home/paged']
        );
    ?>
</div>
